# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec224461bf5b4195b3fec7b9d241343ce00f28babe6219a9fa05d4ddb9e5735524de5a03e566c3f8580667abcc62fe8d7f1e321c8b4f396680bdd291aa0801e1

test:
  secret_key_base: 70ad32b025c418e95e59be2c6b15534c5f833375dffa16fdb686209bef71625457d457a6a58f0cd1de5f0fa4cc48ab32a45f246d8a4beb3201bd8a86eeb4f0ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
